export const PERSONAS = [
  "Michael Jordan",
  "Mike Tyson",
  "Hulk Hogan",
  "Stephen A. Smith",
  "Charles Barkley",
  "Shaquille O'Neal",
  "Deion Sanders",
  "Tom Brady",
  "Aaron Rodgers",
  "Patrick Mahomes",
  "Taylor Swift",
  "Beyonce",
  "Jay-Z",
  "Kanye West",
  "Drake",
  "Justin Bieber",
  "Miley Cyrus",
  "Britney Spears",
  "Michael Jackson",
  "Elvis Presley",
  "Frank Sinatra",
  "Bob Dylan",
  "Johnny Cash",
  "Will Smith",
  "Dwayne 'The Rock' Johnson",
  "Kevin Hart",
  "Adam Sandler",
  "Jim Carrey",
  "Eddie Murphy",
  "Jerry Seinfeld",
  "Larry David",
  "Homer Simpson",
  "Peter Griffin",
  "SpongeBob SquarePants",
  "Donald Trump",
  "Barack Obama",
  "Joe Biden",
  "Bill Clinton",
  "George W. Bush",
  "Arnold Schwarzenegger",
  "Elon Musk",
  "Mark Zuckerberg",
  "Bill Gates",
  "Steve Jobs",
  "Jeff Bezos",
  "Gordon Ramsay",
  "Snoop Dogg",
  "Martha Stewart",
  "Kim Kardashian",
  "Paris Hilton",
  "Tony Robbins"
];

export const ACTIONS = [
  "Trying to espouse a political party that they are not very comfortable with.",
  "Trying to quote Michael Jackson songs during natural conversation.",
  "Trying to sound like a Gen Z'er, but failing badly.",
  "Trying to flirt with the contestant, but doing it very badly.",
  "Recounting a recent doctor's visit.",
  "Complaining about the high cost of groceries.",
  "Trying to sell the contestant a used car with a lot of hidden problems.",
  "Explaining the rules of a board game that they just made up.",
  "Giving a terrible apology for something they did wrong.",
  "Trying to convince the contestant to join a pyramid scheme.",
  "Giving a motivational speech that is not motivating at all.",
  "Trying to use as many corporate buzzwords as possible in conversation.",
  "Describing their very strange and unusual pet.",
  "Trying to get the contestant to go on a date with their friend.",
  "Explaining why they think a certain conspiracy theory is true.",
  "Giving a review of a movie that they clearly didn't understand.",
  "Trying to order a very complicated coffee drink at a cafe.",
  "Complaining about their terrible experience on a recent flight.",
  "Trying to teach the contestant a new dance move, but failing miserably.",
  "Giving their opinion on a very controversial topic."
];
